apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
    # ❌ remove rewrite here too
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: user-service-canary
            port:
              number: 80