apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-stable
  labels:
    app: user-service
    version: stable

spec:
  replicas: 3
  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: user-service
      version: stable

  template:
    metadata:
      labels:
        app: user-service
        version: stable

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: user-service
          image: devopsdevacr7583.azurecr.io/user-service:396002b
          imagePullPolicy: Always

          ports:
            - containerPort: 3001

          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

          env:
            - name: PORT
              value: "3001"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          startupProbe:
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 30
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP

  selector:
    app: user-service
    version: stable

  ports:
    - port: 80
      targetPort: 3001

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service-stable

  minReplicas: 3
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70